# $FreeBSD$

PORTNAME=pfSense-pkg-saml2-auth
PORTVERSION=0.0
PORTREVISION=1
CATEGORIES=sysutils
MASTER_SITES=# empty
DISTFILES=# empty
EXTRACT_ONLY=# empty
MAINTAINER=jaredhendrickson13@gmail.com
COMMENT=pfSense SAML2 Authentication package
LICENSE=APACHE20
NO_BUILD=yes
NO_MTREE=yes
SUB_FILES=pkg-install pkg-deinstall
SUB_LIST=PORTNAME=${PORTNAME}

do-extract:
	 ${MKDIR} ${WRKSRC}

.include <bsd.port.mk>