name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'

# Commit SHAs may differ when trigger via pull request vs workflow_dispatch, ensure the correct commit is referenced.
env:
  commit_id: "${{ github.event.pull_request.head.sha || github.sha }}"
  build_version: "0.0_0dev_${{ github.event.pull_request.head.sha || github.sha }}"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        freebsd_version:
          - FreeBSD-14.0-CURRENT

    steps:
      - uses: actions/checkout@v4
      - name: Setup FreeBSD build VM
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.freebsd_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{ matrix.freebsd_version }} restore initial
          /usr/local/bin/VBoxManage startvm ${{ matrix.freebsd_version }} --type headless
          sleep 5

      - name: Build pfSense-pkg-saml2-auth on FreeBSD
        run: |
          /usr/bin/ssh -o StrictHostKeyChecking=no ${{ matrix.freebsd_version }}.jaredhendrickson.com 'sudo pkill ntpd || true && sudo ntpdate pool.ntp.org || true'
          /usr/local/bin/python3 tools/make_package.py --host ${{ matrix.freebsd_version }}.jaredhendrickson.com --branch ${{ env.commit_id }} --tag ${{ env.build_version }}_${{ matrix.freebsd_version }}

      - name: Teardown FreeBSD build VM
        if: "${{ always() }}"
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.freebsd_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{matrix.freebsd_version}} restore initial

      - uses: actions/upload-artifact@v4
        with:
          name: pfSense-pkg-saml2-auth-${{ env.build_version }}_${{ matrix.freebsd_version }}.pkg
          path: pfSense-pkg-saml2-auth-${{ env.build_version }}_${{ matrix.freebsd_version }}.pkg